# api_spec.yaml
openapi: 3.0.3
info:
  description: A simple API that returns a greeting message.
  title: Greeting API
  version: 1.0.0
security:
  - oauth: []
paths:
  /greet:
    get:
      summary: Returns a greeting message.
      description: 'This endpoint returns a greeting message. It accepts an optional
        query parameter `name`. If `name` is not provided, it defaults to "World".'
      parameters:
        - description: The name of the person to greet.
          example: John
          in: query
          name: name
          required: false
          schema:
            type: string
      security:
        -  oauth: []
      responses:
        200:
          content:
            application/json:
              schema:
                properties:
                    message:
                      description: The greeting message.
                      example: Hello, John!
                      type: string
                type: object
          description: A greeting message.
        400:
          content:
            application/json:
              schema:
                properties:
                  error:
                    description: A description of the error.
                    example: Invalid query parameter
                    type: string
                type: object
          description: Bad Request - Invalid query parameter
